### PR TITLE
Recent search clickable

### PR DESCRIPTION
**Pull request by Jason-M-Bailey**
- recent searches display dynamically
- recent searches are clickable and display in page giphy / wiki results

### CODE REVIEW

**Review by melissarmand — APPROVED** [review]
Looks great!

**Comment by r2sims** [comment]
Approved

**Comment by r2sims** [comment]
Approved

**Review by r2sims — COMMENTED** [review]
Approved

**Review by r2sims — COMMENTED** [review]
approve

**Review by r2sims — APPROVED** [review]

**Pull request merged**
